.TH "MYCLI" "1" "23 March, 2016" "GNU Linux" "My simple util"
.SH "NAME"
mycli \- my little command line tool
.SH "SYNOPSIS"
.sp
.RS 0
mycli
.RE
.SH "DESCRIPTION"
.sp
.PP
Use the \&.Nm macro to refer to your program throughout the man page like
such: Untitled, Underlining is accomplished with the \&.Ar macro like this:
underlined text\&.
.PP
A list of items with descriptions:
.PP
item a   Description of item a
.PP
item b   Description of item b
