.TH "MYCLI" "1" "2016-03-23" "GNU Linux" "My simple util"
.SH "NAME"
.PP
mycli \- my little command line tool
.SH "SYNOPSIS"
.PP
.sp
.RS 0
\fBmycli\fR [\fIcommon_options\fR] [\fB\-\-interactive|\-i\fR] [\fB\-\-param1|\-b\fR \fIint\fR] [\fB\-\-help|\-h\fR]
.RE
.sp
.RS 0
\fBmycli\fR [\fIcommon_options\fR] \fBsubcmd1\fR
.RE
.PP
.RS 12
Here \fIcommon_options\fR are:
.RE
.PP
[\fB\-\-seconds|\-s\fR \fIseconds\fR] [\fB\-\-some\-flag\fR \fIint\fR] [\fB\-\-help|\-h\fR]
.SH "DESCRIPTION"
.PP
Use the \&.Nm macro to refer to your program throughout the man page like
such: Untitled, Underlining is accomplished with the \&.Ar macro like this:
underlined text\&. A list of items with descriptions:
.PP
item a   Description of item a
.PP
item b   Description of item b
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
listitem1 optional  parameters
.sp
.RS 8
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
listitem11
.RE
.sp
.RS 8
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
listitem22
.sp
.RS 12
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
24214 42134 1234 12
.RE
.sp
.RS 12
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
2314 21341 24 12
.RE
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
listitem2
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
listitem3
.RE

.SH "COMMON OPTIONS"
.PP
\fB\-\-help, \-h\fR
.RS 4
Show brief usage information\&.
.RE
.PP
\fB\-\-seconds, \-s\fR \fIseconds\fR
.RS 4
seconds
.RE
.PP
\fB\-\-some\-flag\fR \fIint\fR
.RS 4
second common flag
.RE
.SH "ENVIRONMENT"
.PP
\fBMY_ETCD1\fR
.RS 4
.PP
optional parameters that are not
specific to the utility\&. They specify etcd connection settings, cluster
name and a few more settings\&. By default shardmanctl tries to connect
to the etcd store 127\&.0\&.0\&.1:2379 and use the cluster0 cluster name\&. The
default log level is info\&.
.RE
.PP
\fBMY_ETCD2\fR
.RS 4
.PP
optional parameters that are not
specific to the utility\&. They specify etcd connection settings, cluster
name and a few more settings\&. By default shardmanctl tries to connect
to the etcd store 127\&.0\&.0\&.1:2379 and use the cluster0 cluster name\&. The
default log level is info\&.
.RE
.SH "EXAMPLES"
.PP
\fBInteractive mode\fR
.RS 4
.PP
\fBmycli \-i\fR
.PP
This command runs the \fBmycli\fR in interactive mode
.RE
.sp
.PP
\fBGet command help\fR
.RS 4
.PP
\fBmycli \-h\fR
.PP
It will display help on how to use the command
.RE
.SH "SEE ALSO"
.PP
\fBgroff\fR(1), \fBman\fR(7), \fBman\-pages\fR(7)
